language: php

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
     allow_failures:
         - php: hhvm
         - php: 7.0

before_install:
  - composer self-update

install:
  - composer install
  - composer require satooshi/php-coveralls
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
